---
# tasks file for gitlab
- name: install and run GitLab
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: yes
    state: started
    restart_policy: always
    ports:
      - 443:443
      - 80:80
      - 23:22
    volumes:
      - /gitlab/config:/etc/gitlab
      - /gitlab/logs:/var/log/gitlab
      - /gitlab/data:/var/opt/gitlab