---
# tasks file for base_config
- name: Обновление системы
  apt:
    upgrade: dist

- name: Установка базовых пакетов
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - mc
      - docker
      - docker-compose
      - python3-pip

- name: Добавить докер в автозагрузку
  service:
    name: docker
    state: restarted
