---
# tasks file for base_config
- name: Обновление системы
  apt: 
    upgrade: dist

- name: Установка базовых пакетов
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - mc
      # - snap
      - docker
      - docker-compose
  notify: Добавить докер в автозагрузку