- name: Install GitLab
  hosts: linux
  become: yes

  tasks:
    - name: Upgrade
      apt: 
        upgrade: dist

    - name: install Pack
      apt: 
        name: "{{ packages }}"
      vars:
        packages:
          - mc
          - snap
          - docker
          - docker-compose
