---
# tasks file for samba
- name: install samba pack
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - samba
      - samba-common
      - python-glade2

- name: generate and copy file
  template:
    src: smb.j2
    dest: /etc/samba/smb.conf

- name: create folder
  file:
    path: "{{ item.dest + item.name }}"
    state: directory
    mode: '0755'
  loop:
    "{{ folders }}"

- name: restart samba
  service:
    name: smbd
    state: restarted
